// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyfmSDGm6MbJC8K1QvljKYb7Jt1ACQ3N8',
    appId: '1:1054855425547:web:cbe941e224ad6ce504210e',
    messagingSenderId: '1054855425547',
    projectId: 'flutter-samegame',
    authDomain: 'flutter-samegame.firebaseapp.com',
    storageBucket: 'flutter-samegame.appspot.com',
    measurementId: 'G-Q6T7RC2M6C',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAllVWJx06SGNfYsl7RgWro2TTAhLJ-dRI',
    appId: '1:1054855425547:ios:6b2c9bf960ffd12504210e',
    messagingSenderId: '1054855425547',
    projectId: 'flutter-samegame',
    storageBucket: 'flutter-samegame.appspot.com',
    iosClientId: '1054855425547-id063q8fgsnfcmgnln8jirqd5pna4gsh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSamegame',
  );
}
